host_key_checking:              False
action:                         "maintain"

#OpenStack ssg key name defaulting
os_cloud_name:                  "{{ os_cloud            | default( ( openstack_config is defined and openstack_config.os_cloud is defined ) | ternary( openstack_config.os_cloud,      '' ) ) }}"
os_instancename_prefix:         "{{ instancename_prefix | default( master_role + '-' ) }}"
os_key_name:                    "{{ key_filename        | default( master_role + '-key' ) }}"
os_instance_tags:               "{{ server_tags         | default( master_role ) }}"

#keypair defaulting
computed_ssh_key_path:          "{{ ( '~' | expanduser ) + '/.ssh/' }}"
ansible_user:                   ubuntu
ansible_ssh_user:               ubuntu
ansible_ssh_private_key_file:   "{{ computed_ssh_key_path + os_key_name }}"
##at some point in the future we will need this...
#ansible_python_interpreter:     /usr/bin/python3


#squid defaults (have to be global to be shared accross all meta-roles)
proxy_http_port:                3128
global_dns_server_1:            8.8.8.8
global_dns_server_2:            8.8.4.4
