#node counting and balancing
default_public_count:           2
default_private_count:          0
node_number:                    "{{ node_count                          | default( ( ( public_node_count | default( default_public_count ) ) | int ) + ( ( private_node_count | default( default_private_count ) ) | int ) ) }}"
public_node_number:             "{{ public_node_count                   | default( ( node_number | int ) - ( ( private_node_count | default( default_private_count ) ) | int ) ) }}"
private_node_number:            "{{ private_node_count                  | default( ( node_number | int ) - ( ( ( public_node_number > 0 ) | ternary( public_node_number, default_public_count ) ) | int ) ) }}"


keepalived_version:             1.3.5

virtualrouter_id_idx:           0
virtualrouter_id:               "{{ groups[ 'public_nodes' ][ virtualrouter_id_idx ] }}"
