openstack_config:
  image_name:         Ubuntu 17.10
  flavor_name:        s1-2
  controller_flavor:  s1-2
  #image_name:         CentOS 7
  #flavor_name:        A1.8
  #controller_flavor:  A1.8
  #network_wan:        inap-18000-WAN1110
  #network_lan:        inap-18000-LAN2011
