openstack_config:
  image_name:         Ubuntu 16.04 LTS (Xenial Xerus)
  flavor_name:        A1.1
  controller_flavor:  A1.1
  #image_name:         CentOS 7
  #flavor_name:        A1.8
  #controller_flavor:  A1.8
  #network_wan:        inap-18000-WAN1110
  #network_lan:        inap-18000-LAN2011
