---
# Playbook to ensure docker is installed

- name: launch rancher container with docker
  docker_container:
    name:         rancher-server
    image:        rancher/server
    state:        started
    restart:      yes
    ports:
     - "8080:8080"
  register:       docker_result
  until:          docker_result|success
  retries:        3
  delay:          75
  ignore_errors:  yes
  become:         yes

- name: launch rancher container manually
  shell:          docker run -d --restart=unless-stopped -p 8080:8080 rancher/server
  retries:        3
  delay:          75
  when:           docker_result|failed
  ignore_errors:  yes
  become:         yes
